// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v4.25.3
// source: pkg/protocol/message.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 输入消息结构体
type InputMessageStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd     string `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`         // 命令
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 内容，使用 bytes 类型以便于处理 JSON RawMessage
}

func (x *InputMessageStruct) Reset() {
	*x = InputMessageStruct{}
	mi := &file_pkg_protocol_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputMessageStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputMessageStruct) ProtoMessage() {}

func (x *InputMessageStruct) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputMessageStruct.ProtoReflect.Descriptor instead.
func (*InputMessageStruct) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_message_proto_rawDescGZIP(), []int{0}
}

func (x *InputMessageStruct) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *InputMessageStruct) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// 登录内容结构体
type LoginStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 登录令牌
}

func (x *LoginStruct) Reset() {
	*x = LoginStruct{}
	mi := &file_pkg_protocol_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginStruct) ProtoMessage() {}

func (x *LoginStruct) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginStruct.ProtoReflect.Descriptor instead.
func (*LoginStruct) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_message_proto_rawDescGZIP(), []int{1}
}

func (x *LoginStruct) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 同步离线消息内容结构体
type SyncStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqId uint64 `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"` // 消息序列 ID
}

func (x *SyncStruct) Reset() {
	*x = SyncStruct{}
	mi := &file_pkg_protocol_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStruct) ProtoMessage() {}

func (x *SyncStruct) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStruct.ProtoReflect.Descriptor instead.
func (*SyncStruct) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_message_proto_rawDescGZIP(), []int{2}
}

func (x *SyncStruct) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

// 正常发送消息内容结构体
type MessageStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqId       uint64 `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`                   // 消息序列 ID
	SenderId    uint64 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`          // 发送者 ID
	ClientId    uint64 `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`          // 客户端 ID
	SessionType int32  `protobuf:"varint,4,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"` // 会话类型
	ReceiverId  uint64 `protobuf:"varint,5,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`    // 接收者 ID（单聊接收者 ID 或群聊 group ID）
	Content     string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                             // 消息内容
	SendTime    int64  `protobuf:"varint,7,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`          // 发送时间
}

func (x *MessageStruct) Reset() {
	*x = MessageStruct{}
	mi := &file_pkg_protocol_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStruct) ProtoMessage() {}

func (x *MessageStruct) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStruct.ProtoReflect.Descriptor instead.
func (*MessageStruct) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_message_proto_rawDescGZIP(), []int{3}
}

func (x *MessageStruct) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *MessageStruct) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MessageStruct) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *MessageStruct) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *MessageStruct) GetReceiverId() uint64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *MessageStruct) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageStruct) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

// 输出消息结构体
type OutputMessageStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd     string `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`                        // 命令
	Code    int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`                     // 状态码
	CodeMsg string `protobuf:"bytes,3,opt,name=code_msg,json=codeMsg,proto3" json:"code_msg,omitempty"` // 状态信息
	Content []byte `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                // 内容
}

func (x *OutputMessageStruct) Reset() {
	*x = OutputMessageStruct{}
	mi := &file_pkg_protocol_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputMessageStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputMessageStruct) ProtoMessage() {}

func (x *OutputMessageStruct) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputMessageStruct.ProtoReflect.Descriptor instead.
func (*OutputMessageStruct) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_message_proto_rawDescGZIP(), []int{4}
}

func (x *OutputMessageStruct) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *OutputMessageStruct) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OutputMessageStruct) GetCodeMsg() string {
	if x != nil {
		return x.CodeMsg
	}
	return ""
}

func (x *OutputMessageStruct) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// 确认消息结构体
type AckMsgStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AckType  string `protobuf:"bytes,1,opt,name=ack_type,json=ackType,proto3" json:"ack_type,omitempty"`     // 确认类型
	SeqId    uint64 `protobuf:"varint,2,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`          // 消息序列 ID
	ClientId uint64 `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // 客户端 ID
}

func (x *AckMsgStruct) Reset() {
	*x = AckMsgStruct{}
	mi := &file_pkg_protocol_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMsgStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMsgStruct) ProtoMessage() {}

func (x *AckMsgStruct) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMsgStruct.ProtoReflect.Descriptor instead.
func (*AckMsgStruct) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_message_proto_rawDescGZIP(), []int{5}
}

func (x *AckMsgStruct) GetAckType() string {
	if x != nil {
		return x.AckType
	}
	return ""
}

func (x *AckMsgStruct) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *AckMsgStruct) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

// 输出同步消息结构体
type OutputSyncMsgStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []*MessageStruct `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`                 // 消息内容列表
	HasMore bool             `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"` // 是否还有更多消息
}

func (x *OutputSyncMsgStruct) Reset() {
	*x = OutputSyncMsgStruct{}
	mi := &file_pkg_protocol_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputSyncMsgStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputSyncMsgStruct) ProtoMessage() {}

func (x *OutputSyncMsgStruct) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputSyncMsgStruct.ProtoReflect.Descriptor instead.
func (*OutputSyncMsgStruct) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_message_proto_rawDescGZIP(), []int{6}
}

func (x *OutputSyncMsgStruct) GetContent() []*MessageStruct {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *OutputSyncMsgStruct) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_pkg_protocol_message_proto protoreflect.FileDescriptor

var file_pkg_protocol_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x40, 0x0a, 0x12, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x23, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x23, 0x0a,
	0x0a, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x73,
	0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x65, 0x71,
	0x49, 0x64, 0x22, 0xdb, 0x01, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x70, 0x0a, 0x13, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x64, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x5d, 0x0a, 0x0c, 0x41, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a,
	0x06, 0x73, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73,
	0x65, 0x71, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x63, 0x0a, 0x13, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x4d,
	0x73, 0x67, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x68,
	0x61, 0x73, 0x5f, 0x6d, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68,
	0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_protocol_message_proto_rawDescOnce sync.Once
	file_pkg_protocol_message_proto_rawDescData = file_pkg_protocol_message_proto_rawDesc
)

func file_pkg_protocol_message_proto_rawDescGZIP() []byte {
	file_pkg_protocol_message_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_protocol_message_proto_rawDescData)
	})
	return file_pkg_protocol_message_proto_rawDescData
}

var file_pkg_protocol_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_protocol_message_proto_goTypes = []any{
	(*InputMessageStruct)(nil),  // 0: protocol.InputMessageStruct
	(*LoginStruct)(nil),         // 1: protocol.LoginStruct
	(*SyncStruct)(nil),          // 2: protocol.SyncStruct
	(*MessageStruct)(nil),       // 3: protocol.MessageStruct
	(*OutputMessageStruct)(nil), // 4: protocol.OutputMessageStruct
	(*AckMsgStruct)(nil),        // 5: protocol.AckMsgStruct
	(*OutputSyncMsgStruct)(nil), // 6: protocol.OutputSyncMsgStruct
}
var file_pkg_protocol_message_proto_depIdxs = []int32{
	3, // 0: protocol.OutputSyncMsgStruct.content:type_name -> protocol.MessageStruct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_protocol_message_proto_init() }
func file_pkg_protocol_message_proto_init() {
	if File_pkg_protocol_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_protocol_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_message_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_message_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_message_proto_msgTypes,
	}.Build()
	File_pkg_protocol_message_proto = out.File
	file_pkg_protocol_message_proto_rawDesc = nil
	file_pkg_protocol_message_proto_goTypes = nil
	file_pkg_protocol_message_proto_depIdxs = nil
}
